package generator

const FlakeTemplateEN = `
# Generated by MCFN (English)
{
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05";
  outputs = { self, nixpkgs, ... }: {
    nixosConfigurations.{{.Hostname}} = nixpkgs.lib.nixosSystem {
      modules = [ ./configuration.nix ];
    };
  };
}`

const FlakeTemplateRU = `
# Сгенерировано MCFN (Русский)
{
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05";
  outputs = { self, nixpkgs, ... }: {
    nixosConfigurations.{{.Hostname}} = nixpkgs.lib.nixosSystem {
      modules = [ ./configuration.nix ];
    };
  };
}`
